- name: install license
  command: "/usr/cumulus/bin/cl-license -i /etc/cumulus/license.txt"

- name: restart switchd
  service: name=switchd state=restarted

- name: wait for switchd to start
  wait_for:  path=/var/run/switchd.ready delay=15

- name: reload networking
  service: name=networking state=reloaded

- name: restart ptmd
  service: name=ptmd state=restarted

- name: restart quagga
  service: name=quagga state=restarted
