- name: configure rocket and turtle. give each sudo access
  user: name={{ item }}
        password="$5$rounds=110000$6SXmKAomBOb9INuY$H7SF/896d39R4xX4REGdq/yXUvfBhLkwxREtrQxg9aA"
        update_password=on_create
        groups=sudo
  with_items: [rocket, turtle]

- name: configure MOTD
  template: src=motd.j2 dest=/etc/motd

- name: License switch
  cl_license: >
    src="http://{{ cl_license_server }}/{{ ansible_hostname }}.lic"
  notify:
    - restart switchd

- name: configure ptmd topology.dot
  copy: src=topology.dot dest=/etc/ptm.d/topology.dot
  notify:
    - restart ptmd

- name: disable arp filter
  sysctl: name=net.ipv4.conf.all.arp_filter value=0 state=present reload=yes
